### ISSUE TITLE
Shell Switches causes crash to main menu

### ISSUE THREAD

**Issue by HyperMan19680** [iChun/Sync#182]
I know it's a duplicate, but this issue REALLY needs to be tended to, iChun.

[22:02:56] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel Sync
net.minecraft.util.ReportedException: Loading entity NBT
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1445) ~[sa.class:?]
	at sync.common.packet.PacketNBT.handleClient(PacketNBT.java:46) ~[PacketNBT.class:?]
	at sync.common.packet.PacketNBT.execute(PacketNBT.java:39) ~[PacketNBT.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:84) ~[ChannelHandler$PacketExecuter.class:?]
	at ichun.common.core.network.ChannelHandler$PacketExecuter.channelRead0(ChannelHandler.java:66) ~[ChannelHandler$PacketExecuter.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1367) ~[sa.class:?]
	... 26 more
[22:02:56] [Client thread/INFO] [STDOUT/]: [mcjty.lib.network.SendPreferencesToClientHelper:setPreferences:16]: setPreferences: prefs.getStyle() = STYLE_FLAT_GRADIENT

**Comment by fwyrl** [comment]
For reference, this is also here: #179

**Comment by HyperMan19680** [comment]
I think I found the issue's source. Basically, Morph's morph list, when full of mobs, overloads the NBT data and causes a crash to main menu on syncing to a new shell.
