### ISSUE TITLE
NPE When TE Creates Recipies

### ISSUE THREAD

**Issue by gudenau** [iChun/Sync#191]
When launching Minecraft with TE and Sync installed Sync causes a NPE inside Thermal Expansion.

Minecraft: 1.12.2
Forge: 14.23.0.2495

CodeChicken Lib 1.8+: 1.12-3.1.3.313
CoFH Core: 1.12-4.3.5.13
CoFH World: 1.12-1.0.1.8
iChunUtil: 1.12-7.0.0
Redstone Flux: 1.12-2.0.1.2
Sync: 1.12.2-7.0.0
Thermal Expansion: 1.12.5.3.5.19
Thermal Foundation: 1.12-2.3.5.14

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 10/2/17 11:45 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)
Caused by: java.lang.NullPointerException
	at me.ichun.mods.sync.common.core.RecipeHardcoreFactory.lambda$parse$0(RecipeHardcoreFactory.java:19)
	at me.ichun.mods.ichunutil.common.recipe.ConditionalIngredient.func_193365_a(ConditionalIngredient.java:55)
	at cofh.thermalexpansion.util.managers.machine.CompactorManager.loadRecipes(CompactorManager.java:221)
	at cofh.thermalexpansion.util.managers.machine.CompactorManager.initialize(CompactorManager.java:197)
	at cofh.thermalexpansion.ThermalExpansion.managerInitialize(ThermalExpansion.java:143)
	at cofh.thermalexpansion.ThermalExpansion.postInit(ThermalExpansion.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:611)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:786)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:348)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5426341376 bytes (5174 MB) / 6442450944 bytes (6144 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 12 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -Xmx10G -Xms6G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2495 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version      | Source                                        | Signature                                |
	|:----- |:----------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJ | minecraft         | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJ | mcp               | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJ | FML               | 8.0.99.99    | forge-1.12.2-14.23.0.2495.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | forge             | 14.23.0.2495 | forge-1.12.2-14.23.0.2495.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | codechickenlib    | 3.1.3.313    | CodeChickenLib-1.12-3.1.3.313-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | redstoneflux      | 2.0.1        | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJ | cofhcore          | 4.3.5        | CoFHCore-1.12-4.3.5.13-universal.jar          | None                                     |
	| UCHIJ | cofhworld         | 1.0.1        | CoFHWorld-1.12-1.0.1.8-universal.jar          | None                                     |
	| UCHIJ | ichunutil         | 7.0.0        | iChunUtil-1.12.2-7.0.0.jar                    | None                                     |
	| UCHIJ | sync              | 7.0.0        | Sync-1.12.2-7.0.0.jar                         | None                                     |
	| UCHIJ | thermalfoundation | 2.3.5        | ThermalFoundation-1.12-2.3.5.14-universal.jar | None                                     |
	| UCHIE | thermalexpansion  | 5.3.5        | ThermalExpansion-1.12-5.3.5.19-universal.jar  | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 960/PCIe/SSE2'
```

**Comment by iChun** [comment]
Oh, derp. I know why now. Why is thermal expansion iterating the recipes
though?

**Comment by ichttt** [comment]
Yeah, found it, too. Pushing a fix right now.

**Comment by gudenau** [comment]
It might be for there auto crafting system or something. It supports fluids and they might cache it or something.

No real idea though.

**Comment by ichttt** [comment]
From the code, it's to find recipies which have the same component 4 or 9 times, so their machine can "press" these items into the normal crafting result, so 4 wodden planks -> 1 crafting table in the machine

**Comment by iChun** [comment]
I love how I'm getting issues with all my mods left right center since they've been updated for 1.12.2

**Comment by gudenau** [comment]
Funny that issues 191 and 192 are the same exact thing. :-P

**Comment by iChun** [comment]
#192 was made after #191 was closed, soooo
